### ISSUE TITLE
district Buckow not shown in district filter for Neukölln

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/django_zbp#539] opened 2023-01-23 12:33 UTC
URL: https://bplan-stage.liqd.net/berlin/neukoelln/# and on prod as embed: https://www.berlin.de/ba-neukoelln/politik-und-verwaltung/aemter/stadtentwicklungsamt/stadtplanung/bebauungsplaene/bebauungsplan-fuer-meinberlin/

behaviour: The district filter for the Ortsteil Buckow is not there/shown.
Question: Has it been there before? I cannot say for sure that it has not been there intentionally but I would not see a reason why it was not included in the first place so I guess it is a bug. 

Screenshot:
<img width="725" alt="Bildschirmfoto 2023-01-23 um 13 30 31" src="https://user-images.githubusercontent.com/35491681/214040059-09e099cf-95ea-4392-9f6b-697c2afd7fc9.png">

**Comment by goapunk** [comment] 2023-05-02 12:17
The problem is that Buckow is represented as a MultiPolygon whereas internally we only use Polygon, so it's never actually added to the database. Possible fix would be to migrate the field to MultiPolygon as it should accept regular Polygons as well

**Comment by goapunk** [comment] 2023-05-10 11:41
fixed by #546

**Closed by goapunk** 2023-05-10 11:41 UTC
Labels: bug
